spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: small-services
              uri: lb://small-services
              predicates:
              - Path=/api/v1/small/**
            - id: retail-Material
              predicates:
              - Path=/materials
              uri: lb://retail-Material
  application:
    name: Retail-gateway
  config:
    import: optional:configserver:http://localhost:8190
eureka:
  client:
    fetch-register: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 7991

management:
  endpoint:
    gateway:
      enable: true
    web:
      exposure:
        include: gateway
